#### how many voxels were left after thresholding?

In [7]:
n_vox_each_subj = [out1[si]['best_params'][0].shape[0] for si in range(n_subjects)]
subject_inds = np.concatenate([si*np.ones((n_vox_each_subj[si],),dtype=int) \
                               for si in range(n_subjects)], axis=0)

thresh_sizes = np.zeros((n_subjects, n_rois),dtype=int)
orig_sizes = np.zeros((n_subjects, n_rois),dtype=int)
for ss in range(n_subjects):
    for rr in range(n_rois):
        orig_sizes[ss,rr] = np.sum(roi_def.get_indices(rr) \
                                     & (subject_inds==ss))
        thresh_sizes[ss,rr] = np.sum(roi_def.get_indices(rr) \
                                     & abv_thresh \
                                     & (subject_inds==ss))

In [20]:
pd.DataFrame(orig_sizes, index=subjects, columns=roi_names)

     V1    V2    V3  hV4  V3ab   IPS   OPA   PPA  RSC  OFA   FFA   EBA
1  2392  2096  1632  568   497  1921  1611  1033  566  355   794  2798
2  1630  1496  1467  447   555  2036  1380   994  813  441   869  3195
3  2275  1732  1412  362   656  2117  1330  1251  838  701  1093  3237
4  1526  1297  1139  380   332  2131  1235   960  813  602   942  2889
5  1705  1433  1219  506   358  1532  1332  1221  771  782   907  4050
6  1771  1719  1799  788   373  1792  1362  1229  845  519   826  4005
7  1926  1475  1275  418   586  1452  1083   912  694  316   484  2785
8  1791  1494  1355  417   359  1866  1360   946  799  331  1204  2901

In [171]:
pd.DataFrame(thresh_sizes, index=subjects, columns=roi_names)

     V1    V2    V3  hV4  V3ab  IPS  OPA  PPA  RSC  OFA  FFA  EBA
1  1547  1372  1183  421   204  125  460  222   74  219  263  736
2  1092   878   965  353   200  206  531  408  296  246  386  638
3  1243   986   796  216   176   55   82  151   71  304  156  345
4   797   747   559  157    79   16  198  179  194  176  149  135
5  1078   887   685  288   151  121  430  459   76  366  136  493
6  1123  1025   858  384    78   80  228  179   20  166   79  291
7  1062   838   516  255    37   86  314  129   13  113   98  313
8   767   681   519  227    15   11   78   77    7   95  277  191